pub mod aabb;
pub mod hit;
pub mod layer;
pub mod measure;
pub mod point;
pub mod route;
pub mod scene;
pub mod shape;
pub mod snap;
pub mod spatial;

pub use aabb::Aabb;
pub use hit::{hit_test_shapes, HitKind, HitResult};
pub use layer::Layer;
pub use measure::{measure_points, shape_metrics, MeasureResult, ShapeMetrics};
pub use point::Point;
pub use route::{Route, RouteError, RouteSegment};
pub use scene::Scene;
pub use shape::Shape;
pub use snap::{snap_to_grid, SnappedPosition};
pub use spatial::{query_neighbors, QueryMode, QueryResult, SpatialIndex};
